packages:
  - 'e2e/**'
  - 'packages/**'
  - 'examples/**'
catalogs:
  dev:
    '@types/node': ^24.0.10
    bumpp: ^10.2.0
    execa: ^9.6.0
    jiti: ^2.4.2
    pnpm-workspace-yaml: ^0.3.1
    tinyglobby: ^0.2.14
    tsdown: ^0.12.9
    tsx: ^4.20.3
    typescript: ^5.8.3
    vitest: ^3.2.4
